// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // This is a placeholder for other platforms, feel free to configure them.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQl6m4GtCUuHH2VDkmcXxXNtOXOx6uJk',
    appId: '1:129067762419:web:REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: '129067762419',
    projectId: 'famai-eedea',
    authDomain: 'famai-eedea.firebaseapp.com',
    storageBucket: 'famai-eedea.appspot.com',
    measurementId: 'G-REPLACE_WITH_YOUR_MEASUREMENT_ID',
  );
}
