// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIXe1SAKAG9wRBYGC-g7SnvVXjOu7K9H8',
    appId: '1:129067762419:web:78458c51f5cf77162b6d86',
    messagingSenderId: '129067762419',
    projectId: 'famai-eedea',
    authDomain: 'famai-eedea.firebaseapp.com',
    databaseURL: 'https://famai-eedea-default-rtdb.firebaseio.com',
    storageBucket: 'famai-eedea.firebasestorage.app',
    measurementId: 'G-W53SP8BZYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQl6m4GtCUuHH2VDkmcXxXNtOXOx6uJk',
    appId: '1:129067762419:android:31a9920c8d6b577c2b6d86',
    messagingSenderId: '129067762419',
    projectId: 'famai-eedea',
    databaseURL: 'https://famai-eedea-default-rtdb.firebaseio.com',
    storageBucket: 'famai-eedea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAifNvlnrEtVbErDhJ_NYdFGF8ZTdjeP7o',
    appId: '1:129067762419:ios:110344726773c4c72b6d86',
    messagingSenderId: '129067762419',
    projectId: 'famai-eedea',
    databaseURL: 'https://famai-eedea-default-rtdb.firebaseio.com',
    storageBucket: 'famai-eedea.firebasestorage.app',
    androidClientId: '129067762419-6a8me6ce8385p3uj5j5o14h06qm6el46.apps.googleusercontent.com',
    iosClientId: '129067762419-n1p6r86cjf6eai2t01e4ir4srlum07a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.famai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAifNvlnrEtVbErDhJ_NYdFGF8ZTdjeP7o',
    appId: '1:129067762419:ios:110344726773c4c72b6d86',
    messagingSenderId: '129067762419',
    projectId: 'famai-eedea',
    databaseURL: 'https://famai-eedea-default-rtdb.firebaseio.com',
    storageBucket: 'famai-eedea.firebasestorage.app',
    androidClientId: '129067762419-6a8me6ce8385p3uj5j5o14h06qm6el46.apps.googleusercontent.com',
    iosClientId: '129067762419-n1p6r86cjf6eai2t01e4ir4srlum07a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.famai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIXe1SAKAG9wRBYGC-g7SnvVXjOu7K9H8',
    appId: '1:129067762419:web:1456998cffce77452b6d86',
    messagingSenderId: '129067762419',
    projectId: 'famai-eedea',
    authDomain: 'famai-eedea.firebaseapp.com',
    databaseURL: 'https://famai-eedea-default-rtdb.firebaseio.com',
    storageBucket: 'famai-eedea.firebasestorage.app',
    measurementId: 'G-59RTELDTTS',
  );
}
